export const Phones = [
	{ name: "Apple", path: "/categories/phone/brand/apple" },
	{ name: "Samsung", path: "/categories/phone/brand/samsung" },
	{ name: "OPPO", path: "/categories/phone/brand/oppo" },
	{ name: "VIVO", path: "/categories/phone/brand/vivo" },
	{ name: "Mi", path: "/categories/phone/brand/mi" },
	{ name: "One Plus", path: "/categories/phone/brand/oneplus" },
	{ name: "INFINIX", path: "/categories/phone/brand/infinix" },
	{ name: "POCO", path: "/categories/phone/brand/poco" },
	{ name: "Redmi", path: "/categories/phone/brand/redmi" },
	{ name: "Realme", path: "/categories/phone/brand/realme" },
	{ name: "IQOO", path: "/categories/phone/brand/iqoo" },
	{ name: "Nokia", path: "/categories/phone/brand/nokia" },
	{ name: "ASUS", path: "/categories/phone/brand/asus" },
	{ name: "LG", path: "/categories/phone/brand/lg" },
	{ name: "LAVA", path: "/categories/phone/brand/lava" },
	{ name: "Lenovo", path: "/categories/phone/brand/lenovo" },
	{ name: "Micromax", path: "/categories/phone/brand/micromax" },
	{ name: "Karbon", path: "/categories/phone/brand/karbon" },
	{ name: "Honor", path: "/categories/phone/brand/honor" }
];

export const Accessories = [
  { name: "Headphones", path: "/categories/sub/headphones" },
  { name: "Earpods", path: "/categories/sub/earpods" },
  { name: "Boomed Headset", path: "/categories/sub/boomed headset" },
  { name: "Pendrive", path: "/categories/sub/pendrive" },
  { name: "Keyboard", path: "/categories/sub/keyboard" },
  { name: "Mouse", path: "/categories/sub/mouse" },
  { name: "Phone Case", path: "/categories/sub/phone case" },
  { name: "Memory Card", path: "/categories/sub/memory card" },
  { name: "Charger", path: "/categories/sub/charger" },
  { name: "HDD", path: "/categories/sub/hdd" },
  { name: "SSD", path: "/categories/sub/ssd" },
  { name: "Sticker", path: "/categories/sub/sticker" },
  { name: "Toch Pen", path: "/categories/sub/toch pen" },
  { name: "Card Reader", path: "/categories/sub/card reader" },
  { name: "USB Cable", path: "/categories/sub/usb cable" },
  { name: "USB Hub", path: "/categories/sub/usb hub" },
  { name: "Mouse pad", path: "/categories/sub/mouse pad" },
  { name: "Pen", path: "/categories/sub/pen" },
  { name: "Desktop Mat", path: "/categories/sub/desktop mat" },
  { name: "Bluetooth Adapters", path: "/categories/sub/bluetooth adapters" },
  { name: "Home Audio", path: "/categories/sub/home audio" },
  { name: "Smart Watches", path: "/categories/sub/smart watches" },
  { name: "Monitors", path: "/categories/sub/monitors" },
  { name: "Printers", path: "/categories/sub/printers" },
  { name: "PowerBank", path: "/categories/sub/powerbank" },
  { name: "Smart Home", path: "/categories/sub/smart home" },
];

export const Brands = [
	 { name: "Amazon", path: "/brand/amazon" },
  { name: "AO Smith", path: "/brand/ao smith" },
  { name: "Apple", path: "/brand/apple" },
  { name: "ASUS", path: "/brand/asus" },
  { name: "Atomberg", path: "/brand/atomberg" },
  { name: "Bajaj", path: "/brand/bajaj" },
  { name: "Blue Star", path: "/brand/blue star" },
  { name: "Boat", path: "/brand/boat" },
  { name: "Borosil", path: "/brand/borosil" },
  { name: "Bosch", path: "/brand/bosch" },
  { name: "Bose", path: "/brand/bose" },
  { name: "Butterfly", path: "/brand/butterfly" },
  { name: "Conekt", path: "/brand/conekt" },
  { name: "Cool-Touch", path: "/brand/cool-touch" },
  { name: "Crompton", path: "/brand/crompton" },
  { name: "Daikin", path: "/brand/daikin" },
  { name: "Dyson", path: "/brand/dyson" },
  { name: "Elephant", path: "/brand/elephant" },
  { name: "Elica", path: "/brand/elica" },
  { name: "FABER", path: "/brand/faber" },
  { name: "Fingers", path: "/brand/fingers" },
  { name: "Fire-Boltt", path: "/brand/fire-boltt" },
  { name: "Fujitsu General", path: "/brand/fujitsu general" },
  { name: "Godrej", path: "/brand/godrej" },
  { name: "Gripp", path: "/brand/gripp" },
  { name: "Haier", path: "/brand/haier" },
  { name: "HapiPola", path: "/brand/hapipola" },
  { name: "HP", path: "/brand/hp" },
  { name: "IFB", path: "/brand/ifb" },
  { name: "Inbase", path: "/brand/inbase" },
  { name: "Itel", path: "/brand/itel" },
  { name: "JBL", path: "/brand/jbl" },
  { name: "Lenovo", path: "/brand/lenovo" },
  { name: "LG", path: "/brand/lg" },
  { name: "Marshall", path: "/brand/marshall" },
  { name: "Mi", path: "/brand/mi" },
  { name: "Microsoft", path: "/brand/microsoft" },
  { name: "New Case", path: "/brand/new case" },
  { name: "Noise", path: "/brand/noise" },
  { name: "Nokia", path: "/brand/nokia" },
  { name: "OnePlus", path: "/brand/oneplus" },
  { name: "Oppo", path: "/brand/oppo" },
  { name: "Orient", path: "/brand/orient" },
  { name: "Panasonic", path: "/brand/panasonic" },
  { name: "Pc", path: "/brand/pc" },
  { name: "Philips", path: "/brand/philips" },
  { name: "Preethi", path: "/brand/preethi" },
  { name: "Premier", path: "/brand/premier" },
  { name: "Prestige", path: "/brand/prestige" },
  { name: "Realme", path: "/brand/realme" },
  { name: "Redmi", path: "/brand/redmi" },
  { name: "Robocare", path: "/brand/robocare" },
  { name: "Samsung", path: "/brand/samsung" },
  { name: "SanDisk", path: "/brand/sandisk" },
  { name: "Sony", path: "/brand/sony" },
  { name: "Symphony", path: "/brand/symphony" },
  { name: "TCL", path: "/brand/tcl" },
  { name: "Tecno", path: "/brand/tecno" },
  { name: "Trumbote", path: "/brand/trumbote" },
  { name: "Ultra", path: "/brand/ultra" },
  { name: "Usha", path: "/brand/usha" },
  { name: "V-Guard", path: "/brand/v-guard" },
  { name: "Venus", path: "/brand/venus" },
  { name: "Vidiem", path: "/brand/vidiem" },
  { name: "Vivo", path: "/brand/vivo" },
  { name: "Voltas", path: "/brand/voltas" },
  { name: "Whirlpool", path: "/brand/whirlpool" },
  { name: "Wonderchef", path: "/brand/wonderchef" },
  { name: "Xiaomi", path: "/brand/xiaomi" },
  { name: "Zebronics", path: "/brand/zebronics" }
]